name: flutter_screen_scaler
description: A package to resize your widgets according to the screen size with the use of percentages.
version: 2.1.0
homepage: https://github.com/akassharjun/flutter-screen-scaler

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
