name: flutter_screen_scaler
description: A package to scale widgets and font sizes based on screen percentages, with convenient extension methods (e.g., `50.h`, `30.w`, `16.sp`).
version: 3.0.0
homepage: https://github.com/akassharjun/flutter-screen-scaler

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
